package com.sendmefile77.chronosphere.adult

internal data class AdultVisualRecipe(
    val id: String,
    val eventCodes: Set<String>,
    val sceneFamily: String,
    val rigLayout: String,
    val poseKey: String,
    val wardrobeKey: String,
    val settingKey: String,
    val cameraKey: String,
    val lightingKey: String,
    val effectTags: Set<String>,
    val minParticipants: Int = 1,
    val maxParticipants: Int = 8,
    val requiredTags: Set<String> = emptySet(),
    val forbiddenTags: Set<String> = emptySet(),
    val requiredEras: Set<String> = emptySet(),
    val forbiddenEras: Set<String> = emptySet(),
    val eraWeights: Map<String, Double> = emptyMap(),
    val numericWeights: Map<String, Double> = emptyMap(),
    val weight: Double = 1.0,
    val rigPlan: RigPlan = RigPlan.BASELINE,
    val requiredPosture: String = "",
    val requiredCovering: String = "",
    val minArms: Int = 2,
    val maxArms: Int = 2,
    val minLegs: Int = 2,
    val maxLegs: Int = 2,
    val minEyes: Int = 1,
    val maxEyes: Int = 2,
    val requireTail: Boolean = false,
    val forbidTail: Boolean = true,
    val minDivergence: Double? = null,
    val maxDivergence: Double? = 0.44,
    val requireHybrid: Boolean = false,
    val wardrobeState: AdultWardrobeState? = null,
)

internal val SAFE_VISUAL_FALLBACK = AdultVisualRecipe(
    id = "fallback.silhouette.hold",
    eventCodes = emptySet(),
    sceneFamily = "symbolic",
    rigLayout = "solo-bust",
    poseKey = "pose.hold",
    wardrobeKey = "wardrobe.opaque",
    settingKey = "set.threshold",
    cameraKey = "cam.portrait",
    lightingKey = "light.low",
    effectTags = setOf("fallback", "silhouette"),
    minParticipants = 1,
    maxParticipants = 99,
    weight = 1.0,
    rigPlan = RigPlan.SILHOUETTE,
    minArms = 0,
    maxArms = 16,
    minLegs = 0,
    maxLegs = 16,
    minEyes = 0,
    maxEyes = 16,
    forbidTail = false,
    maxDivergence = null,
)

internal val SAFE_UNDRESSED_FALLBACK = AdultVisualRecipe(
    id = "fallback.silhouette.undressed",
    eventCodes = setOf("CHARACTER_CARD"),
    sceneFamily = "character-card",
    rigLayout = "morph-bust",
    poseKey = "pose.card-idle",
    wardrobeKey = "wardrobe.undressed",
    settingKey = "set.card",
    cameraKey = "cam.portrait",
    lightingKey = "light.soft",
    effectTags = setOf("fallback", "silhouette", "morph-safe", "undressed"),
    minParticipants = 1,
    maxParticipants = 99,
    weight = 1.0,
    rigPlan = RigPlan.SILHOUETTE,
    minArms = 0,
    maxArms = 16,
    minLegs = 0,
    maxLegs = 16,
    minEyes = 0,
    maxEyes = 16,
    forbidTail = false,
    maxDivergence = null,
    wardrobeState = AdultWardrobeState.UNDRESSED,
)
