package com.sendmefile77.chronosphere.adult

internal object BundledVisualRecipes {
    val all: List<AdultVisualRecipe> = listOf(
        rec("courtship.garden.clothed", setOf("COURTSHIP"), "courtship", "pair-standing", "pose.lean-close", "wardrobe.clothed", "set.garden", "cam.three-quarter", "light.day", setOf("clothed", "tender"), minP = 1, maxP = 2, eraW = mapOf(EraTags.TRIBAL to 0.3, EraTags.AGRARIAN to 0.2)),
        rec("scandal.court.exposure", setOf("SCANDAL"), "scandal", "crowd-facing", "pose.accused", "wardrobe.rumpled", "set.court", "cam.wide", "light.harsh", setOf("exposure", "crowd"), minP = 1, maxP = 8),
        rec("union.chamber.missionary", setOf("UNION"), "coupling", "pair-bed", "pose.missionary", "wardrobe.undressed", "set.chamber", "cam.intimate", "light.lamp", setOf("penetration", "sex"), minP = 2, maxP = 2),
        rec("union.chamber.behind", setOf("UNION"), "coupling", "pair-bed", "pose.from-behind", "wardrobe.hiked", "set.chamber", "cam.over-shoulder", "light.lamp", setOf("penetration", "sex"), minP = 2, maxP = 2, weight = 0.8),
        rec("union.loft.industrial", setOf("UNION"), "coupling", "pair-bed", "pose.missionary", "wardrobe.undressed", "set.loft", "cam.intimate", "light.neon", setOf("penetration", "sex", "industrial"), minP = 2, maxP = 2, weight = 1.4, requiredEras = EraTags.INDUSTRIAL_PLUS, eraW = mapOf(EraTags.INDUSTRIAL to 0.4, EraTags.ELECTRIC to 0.3, EraTags.INFORMATION to 0.3)),
        rec("affair.hidden.clandestine", setOf("AFFAIR"), "coupling", "pair-wall", "pose.upright-fuck", "wardrobe.half-on", "set.hidden-room", "cam.close", "light.slit", setOf("adultery", "penetration"), minP = 2, maxP = 2),
        rec("dynastic.palace.heirbed", setOf("DYNASTIC_BOND", "SUCCESSION_BED"), "coupling", "pair-bed", "pose.missionary", "wardrobe.regalia-open", "set.palace", "cam.formal", "light.gold", setOf("heir", "penetration"), minP = 2, maxP = 2, numW = mapOf(SocialContextKeys.WEALTH to 0.25, SocialContextKeys.STATUS to 0.2)),
        rec("fertility.shrine.creampie", setOf("FERTILITY_RITE", "CUM_RITE"), "ritual-sex", "pair-altar", "pose.seed-rite", "wardrobe.ceremonial-open", "set.shrine", "cam.low", "light.flame", setOf("creampie", "ritual", "fluids"), minP = 2, maxP = 8),
        rec("patronage.salon.transaction", setOf("PATRONAGE_LIAISON"), "coupling", "pair-chaise", "pose.seated-straddle", "wardrobe.parted", "set.salon", "cam.side", "light.candle", setOf("transaction", "sex"), minP = 2, maxP = 2, numW = mapOf(SocialContextKeys.WEALTH to 0.35, SocialContextKeys.SCARCITY to -0.3)),
        rec("concubine.annex.kept", setOf("CONCUBINAGE"), "coupling", "pair-divan", "pose.side-entry", "wardrobe.sheer", "set.annex", "cam.intimate", "light.amber", setOf("harem", "sex"), minP = 2, maxP = 4),
        rec("sacred.temple.union", setOf("SACRED_UNION"), "ritual-sex", "pair-kneel", "pose.sacred-join", "wardrobe.vestment-open", "set.temple", "cam.icon", "light.shaft", setOf("ritual", "sex"), minP = 2, maxP = 2),
        rec("taboo.threshold.break", setOf("TABOO_BREAK"), "coupling", "pair-door", "pose.against-frame", "wardrobe.torn", "set.threshold", "cam.tight", "light.edge", setOf("forbidden", "sex"), minP = 2, maxP = 2),
        rec("secret.locked.coupling", setOf("SECRET_COUPLING"), "coupling", "pair-bed", "pose.muffled-fuck", "wardrobe.nightclothes-off", "set.locked-room", "cam.close", "light.dark", setOf("clandestine", "penetration"), minP = 2, maxP = 2),
        rec("rough.bed.pounding", setOf("ROUGH_COUPLING", "POWER_FUCK"), "hardcore", "pair-bed", "pose.prone-bone", "wardrobe.ripped", "set.bedchamber", "cam.low", "light.hard", setOf("rough-sex", "penetration", "sweat"), minP = 2, maxP = 2),
        rec("power.wartent.claim", setOf("POWER_FUCK"), "hardcore", "pair-cot", "pose.standing-lift", "wardrobe.armor-open", "set.war-tent", "cam.three-quarter", "light.lantern", setOf("power", "rough-sex"), minP = 2, maxP = 2, weight = 0.9, numW = mapOf(SocialContextKeys.WAR_PRESSURE to 0.6)),
        rec("anal.hidden.pair", setOf("ANAL_UNION"), "hardcore", "pair-bed", "pose.anal-kneel", "wardrobe.stripped", "set.hidden-room", "cam.close", "light.slit", setOf("anal", "penetration"), minP = 2, maxP = 2, forbidden = AdultCulture.AUSTERE),
        rec("orgy.feast.group", setOf("ORGY", "HAREM_NIGHT"), "group-sex", "group-floor", "pose.pile", "wardrobe.discarded", "set.feast-hall", "cam.wide", "light.torch", setOf("group", "penetration", "fluids"), minP = 3, maxP = 12),
        rec("harem.annex.service", setOf("HAREM_SERVICE", "HAREM_NIGHT"), "group-sex", "group-divan", "pose.oral-circle", "wardrobe.sheer", "set.annex", "cam.wide", "light.amber", setOf("harem", "oral", "penetration"), minP = 2, maxP = 10),
        rec("public.plaza.exhibition", setOf("PUBLIC_SEX"), "hardcore", "pair-square", "pose.bent-over-crowd", "wardrobe.hiked", "set.plaza", "cam.wide", "light.noon", setOf("exhibition", "penetration"), minP = 2, maxP = 8, forbidden = AdultCulture.AUSTERE, numW = mapOf(SocialContextKeys.URBANIZATION to 0.35)),
        rec("public.arcade.neon", setOf("PUBLIC_SEX"), "hardcore", "pair-square", "pose.bent-over-crowd", "wardrobe.hiked", "set.arcade", "cam.wide", "light.neon", setOf("exhibition", "penetration", "urban"), minP = 2, maxP = 8, forbidden = AdultCulture.AUSTERE, requiredEras = setOf(EraTags.URBAN, EraTags.INDUSTRIAL, EraTags.ELECTRIC, EraTags.INFORMATION), eraW = mapOf(EraTags.INFORMATION to 0.4, EraTags.URBAN to 0.3)),
        rec("bondage.cellar.restraint", setOf("BONDAGE_RITE"), "hardcore", "pair-frame", "pose.bound-spread", "wardrobe.straps", "set.cellar", "cam.low", "light.ember", setOf("bdsm", "restraint", "power"), minP = 2, maxP = 4),
        rec("altar.coupling.rite", setOf("ALTAR_COUPLING", "FERTILITY_RITE"), "ritual-sex", "pair-altar", "pose.altar-mount", "wardrobe.ceremonial-open", "set.altar", "cam.low", "light.flame", setOf("ritual", "penetration"), minP = 2, maxP = 6),
        rec("hold.threshold.silhouette", setOf("CONTEXT_HOLD"), "symbolic", "solo-bust", "pose.hold", "wardrobe.opaque", "set.threshold", "cam.portrait", "light.low", setOf("fallback", "hold"), minP = 1, maxP = 99, plan = RigPlan.SILHOUETTE, minA = 0, maxA = 16, minL = 0, maxL = 16, minE = 0, maxE = 16, noTail = false, maxDiv = null),
        rec("union.hybrid.blend", setOf("UNION", "AFFAIR", "DYNASTIC_BOND"), "coupling", "hybrid-pair-bed", "pose.missionary-blend", "wardrobe.undressed", "set.chamber", "cam.intimate", "light.lamp", setOf("penetration", "sex", "hybrid"), minP = 2, maxP = 2, weight = 1.35, plan = RigPlan.HYBRID, hybrid = true, maxDiv = 0.85),
        rec("courtship.hybrid.garden", setOf("COURTSHIP"), "courtship", "hybrid-pair-standing", "pose.lean-close", "wardrobe.clothed", "set.garden", "cam.three-quarter", "light.day", setOf("clothed", "tender", "hybrid"), minP = 1, maxP = 2, weight = 1.2, plan = RigPlan.HYBRID, hybrid = true, maxDiv = 0.85),
        rec("union.divergent.quad", setOf("UNION", "ROUGH_COUPLING"), "coupling", "quad-pair-bed", "pose.entwined-limbs", "wardrobe.undressed", "set.chamber", "cam.wide", "light.lamp", setOf("penetration", "sex", "divergent"), minP = 2, maxP = 2, weight = 1.5, plan = RigPlan.DIVERGENT, minA = 3, maxA = 6, noTail = false, minDiv = 0.2, maxDiv = 1.0),
        rec("union.divergent.tailed", setOf("UNION", "AFFAIR", "FERTILITY_RITE"), "coupling", "tailed-pair-bed", "pose.coil-mount", "wardrobe.undressed", "set.chamber", "cam.intimate", "light.lamp", setOf("penetration", "sex", "tail"), minP = 2, maxP = 2, weight = 1.4, plan = RigPlan.DIVERGENT, needTail = true, noTail = false, minDiv = 0.15, maxDiv = 1.0),
        rec("union.divergent.scaled", setOf("UNION", "SACRED_UNION"), "coupling", "scaled-pair-bed", "pose.missionary", "wardrobe.none", "set.chamber", "cam.intimate", "light.cool", setOf("penetration", "sex", "scales"), minP = 2, maxP = 2, weight = 1.3, plan = RigPlan.DIVERGENT, covering = "scales", noTail = false, minDiv = 0.2, maxDiv = 1.0),
        rec("rough.divergent.semi", setOf("ROUGH_COUPLING", "POWER_FUCK"), "hardcore", "stooped-pair", "pose.prone-bone", "wardrobe.ripped", "set.war-tent", "cam.low", "light.lantern", setOf("rough-sex", "penetration", "divergent"), minP = 2, maxP = 2, weight = 1.2, plan = RigPlan.DIVERGENT, posture = "semi_upright", noTail = false, minDiv = 0.2, maxDiv = 1.0),
    )

    private fun rec(
        id: String, events: Set<String>, family: String, rig: String, pose: String, wardrobe: String,
        setting: String, camera: String, light: String, effects: Set<String>,
        minP: Int = 1, maxP: Int = 8, weight: Double = 1.0, forbidden: Set<String> = emptySet(),
        requiredEras: Set<String> = emptySet(), eraW: Map<String, Double> = emptyMap(), numW: Map<String, Double> = emptyMap(),
        plan: RigPlan = RigPlan.BASELINE, posture: String = "", covering: String = "",
        minA: Int = 2, maxA: Int = 2, minL: Int = 2, maxL: Int = 2, minE: Int = 1, maxE: Int = 2,
        needTail: Boolean = false, noTail: Boolean = true, minDiv: Double? = null, maxDiv: Double? = 0.44,
        hybrid: Boolean = false,
    ) = AdultVisualRecipe(
        id = id, eventCodes = events, sceneFamily = family, rigLayout = rig, poseKey = pose,
        wardrobeKey = wardrobe, settingKey = setting, cameraKey = camera, lightingKey = light,
        effectTags = effects, minParticipants = minP, maxParticipants = maxP, forbiddenTags = forbidden,
        requiredEras = requiredEras, eraWeights = eraW, numericWeights = numW, weight = weight,
        rigPlan = plan, requiredPosture = posture, requiredCovering = covering,
        minArms = minA, maxArms = maxA, minLegs = minL, maxLegs = maxL, minEyes = minE, maxEyes = maxE,
        requireTail = needTail, forbidTail = noTail, minDivergence = minDiv, maxDivergence = maxDiv,
        requireHybrid = hybrid,
    )
}
